### ISSUE TITLE
docker container fails to start

### ISSUE THREAD

**Issue by briodan** [drndos/openspoolman#10]
trying to get the docker container spun up but its not starting see below for error logs. the key one I think is this line as it seems to no include the Spoolman URL in a request

```
requests.exceptions.MissingSchema: Invalid URL 'None/api/v1/spool': No scheme supplied. Perhaps you meant https://None/api/v1/spool?
```

this is the docker config
```
version: '3.8'
services:
  openspoolman:
    image: ghcr.io/drndos/openspoolman:0.1.3
    container_name: openspoolman  
    ports:
      - "8080:8000"
```

env variables are set and the Spoolman base url is accessible

![Image](https://github.com/user-attachments/assets/90e03940-5c5c-4692-b668-3eb5bde194fd)

Full Log attached

[_openspoolman_logs.txt](https://github.com/user-attachments/files/18481272/_openspoolman_logs.txt)

**Comment by logikal** [comment]
Looks like portainer? you need to actually get the env vars from portainer to your compose, like so:

```yaml
...
    environment:
      OPENSPOOLMAN_BASE_URL: ${OPENSPOOLMAN_BASE_URL}
      PRINTER_ACCESS_CODE: ${PRINTER_ACCESS_CODE}
      PRINTER_ID: ${PRINTER_ID}
      PRINTER_IP: ${PRINTER_IP}
      SPOOLMAN_BASE_URL: ${SPOOLMAN_BASE_URL}
      AUTO_SPEND: ${AUTO_SPEND}
```
